##### AIM:
To write Python program to perform simple arithmetic operations on 2D arrays using
NumPy package.

In [1]:
import numpy as np

In [2]:
#this function returns the sum of two matrices 
def fn_mat_sum(mat_a, mat_b):
    if mat_a.shape == mat_b.shape:
        mat_sum = mat_a + mat_b
    else:
        mat_sum = None
    return mat_sum

In [3]:
#This function returns the difference of two matrices
def fn_mat_diff(mat_a, mat_b):
    if mat_a.shape == mat_b.shape:
        mat_diff = mat_a - mat_b
    else:
        mat_diff = None
    return mat_diff

In [4]:
#this function returns the multiplication of two matrices
def fn_mat_mul(mat_a, mat_b):
    if mat_a.shape[1] == mat_b.shape[0]:
        mat_mul = np.dot(mat_a, mat_b)
    else:
        mat_mul = None
    return mat_mul

In [5]:
#this functions returns the subset of given matrix using row,column indexex
def fn_subset_mat(mat, r1, c1, r2, c2):
    
    if (r1>-1) and (c1>-1) and (r1<r2) and (c1<c2) and r2<mat.shape[0] and c2<mat.shape[1]:    
        res = mat[r1:r2, c1:c2]
    else:
        res = None
    return res

In [17]:
#this is main function
if __name__ == "__main__":
    np.random.seed(3);
    ip_mat_a = np.random.randint(1, 20, size=(3, 3)); print("A=\n",ip_mat_a)
    ip_mat_b = np.random.randint(1, 20, size=(3, 3)); print("B=\n",ip_mat_b)
    ip_mat_c = np.random.randint(1, 20, size=(5, 5)); print("C=\n",ip_mat_c)
    res_sum = fn_mat_sum(ip_mat_a, ip_mat_b)
    res_diff = fn_mat_diff(ip_mat_a, ip_mat_b)
    res_mul = fn_mat_mul(ip_mat_a, ip_mat_b)
    res_subset_mat = fn_subset_mat(ip_mat_c, r1=1, c1=1, r2=3, c2=3)
    print("Sum:\n", res_sum)
    print("Diff:\n", res_diff)
    print("Mult:\n", res_mul)
    print("Subset:\n",res_subset_mat)

A=
 [[11  4  9]
 [ 1 11 12]
 [10 11  7]]
B=
 [[ 1 13  8]
 [15 18  3]
 [ 3  2  6]]
C=
 [[ 9 15  2 11  8]
 [12  2 16 17  6]
 [18 15  1  1 10]
 [19  6  8  6 15]
 [ 2 18  2 11 12]]
Sum:
 [[12 17 17]
 [16 29 15]
 [13 13 13]]
Diff:
 [[ 10  -9   1]
 [-14  -7   9]
 [  7   9   1]]
Mult:
 [[ 98 233 154]
 [202 235 113]
 [196 342 155]]
Subset:
 [[ 2 16]
 [15  1]]
